# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_PRIORITY = "8"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fp01"
BBFILE_PATTERN_fp01 = "^${LAYERDIR}/"
LAYERVERSION_fp01 = "1"
LAYERSERIES_COMPAT_fp01 = "kirkstone langdale honister"
