# Configuration script used by ntpdate-sync script

NTPSERVERS="ntp.yandex.net hwwbus.pt.cloud.yandex-team.ru hwwbus.gpn.cloud.yandex-team.ru pool.ntp.org"

# Set to "yes" to write time to hardware clock on success
UPDATE_HWCLOCK="yes"
