KMACHINE = "aspeed"
KERNEL_DEVICETREE = "aspeed/${KMACHINE}-bmc-ucode-dalegibbs.dtb"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-aspeed"
PREFERRED_PROVIDER_u-boot = "u-boot-aspeed"
PREFERRED_PROVIDER_u-boot-fw-utils = "u-boot-fw-utils-aspeed"
UBOOT_MACHINE = "ast_g5_phy_config"
# UBOOT_MACHINE = "evb-ast2500_defconfig"
# UBOOT_DEVICETREE = "ast2500-evb"

require conf/machine/include/ast2500.inc
require conf/machine/include/obmc-bsp-common.inc
require dalegibbs.inc

FLASH_SIZE = "32768"
# FLASH_UBOOT_OFFSET:flash-65536 = "0"
# FLASH_UBOOT_ENV_OFFSET:flash-65536 = "1024"
# FLASH_KERNEL_OFFSET:flash-65536 = "2048"

FLASH_ROFS_OFFSET = "4992"
FLASH_RWFS_OFFSET = "28800"

# # We don't have configuration for these components yet, so remove them.
# PREFERRED_PROVIDER_virtual/obmc-fan-mgmt = "tyan-dummy"
# IMAGE_FEATURES:remove = "obmc-fan-control"
# IMAGE_FEATURES:remove = "obmc-fan-mgmt"
# IMAGE_FEATURES:remove = "obmc-flash-mgmt"

PREFERRED_PROVIDER_virtual/phosphor-led-manager-config-native = "breath-led-manager-config-native"
