KMACHINE = "aspeed"

UBOOT_MACHINE = "ast_g5_phy_config"
UBOOT_ENTRYPOINT = "0x40008000"
UBOOT_LOADADDRESS = "0x40008000"

FLASH_SIZE = "64512"

FLASH_UBOOT_OFFSET = "0"
FLASH_UBOOT_SPL_SIZE = "64"
FLASH_KERNEL_OFFSET = "512"
FLASH_ROFS_OFFSET = "4864"
FLASH_RWFS_OFFSET = "37632"
RWFS_SIZE = "20971520"

require conf/machine/include/ast2500.inc
require conf/machine/include/obmc-bsp-common.inc
require conf/machine/include/yandex.inc

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-aspeed"
PREFERRED_PROVIDER_u-boot = "u-boot-aspeed"
PREFERRED_PROVIDER_u-boot-fw-utils = "u-boot-fw-utils-aspeed"
