KMACHINE = "aspeed"
MACHINE = "fp01"
KERNEL_DEVICETREE = "${KMACHINE}-yandex-${MACHINE}.dtb"

require meta-common/conf/ucode-g5.conf

IMAGE_INSTALL:append = "cpld-updater nvme-cooler crashdump-bin cjson host-error-monitor"

#OBMC_ORG_YAML_SUBDIRS += "com/intel"
#OVERRIDES .= ":intel"