
# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/meta-common/recipes-*/*/*.bb \
            ${LAYERDIR}/meta-common/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "yandex"
BBFILE_PATTERN_yandex = "^${LAYERDIR}/"
LAYERVERSION_yandex = "1"

LAYERSERIES_COMPAT_yandex = "kirkstone langdale honister"
YANDEXBASE = '${@os.path.normpath("${LAYERDIR}/")}'

BBFILE_PRIORITY = "8"
