FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"
SRC_URI:remove = " file://0001-configs-ast-Add-redundnant-env.patch"
SRC_URI:append = " file://0001-Add-passthrough-gpio-function-and-video-enable.patch"
SRC_URI:append = " file://0006-Add-earlyprintk-to-default-bootargs.patch"
SRC_URI:append = " file://0007-Disable-P2A-peripheral-to-block-socflash.patch"
SRC_URI:append = " file://0009-Apply-WDT1-2-reset-mask-to-reset-needed-controller.patch"
SRC_URI:append = " file://0012-Add-reset-reason-to-cpuinfo-and-to-kernel-cmdline.patch"
SRC_URI:append = " file://0013-Aspeed-G5-I2C-support.patch"
SRC_URI:append = " file://0014-Aspeed-G5-IRQ-support.patch"
SRC_URI:append = " file://0016-Introduce-Yandex-routines.patch"
SRC_URI:append = " file://0017-Introduce-IPMI-via-KCS-in-U-Boot.patch"
SRC_URI:append = " file://0018-FIX-Drop-bits-to-avoid-BMCINT-generation.patch"

CFLAGS += "-DMACHINE_${MACHINE}"
