# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_PRIORITY = "8"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb2600"
BBFILE_PATTERN_evb2600 = "^${LAYERDIR}/"
LAYERVERSION:evb2600 = "1"
LAYERSERIES_COMPAT_evb2600 = "kirkstone langdale honister"
