KMACHINE = "aspeed"
KERNEL_DEVICETREE = "aspeed/${MACHINE}-ast2500-evb.dtb"

UBOOT_MACHINE = "evb-ast2500_defconfig"
UBOOT_DEVICETREE = "ast2500-evb"

require conf/machine/include/ucode.inc
require conf/machine/include/ast2500.inc
require conf/machine/include/obmc-evb-common.inc

SERIAL_CONSOLES = "115200;ttyS4"

FLASH_SIZE = "32768"

VIRTUAL-RUNTIME_skeleton_workbook = "${MACHINE}-config"

PREFERRED_PROVIDER_virtual/phosphor-led-manager-config-native = "breath-led-manager-config-native"
# PREFERRED_PROVIDER_virtual/openpower-occ-control-config-native = "breath-occ-control-config-native"

OBMC_CHASSIS_INSTANCES = "0"

