FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

#Enable threshold monitoring
EXTRA_OECMAKE += "-DSEL_LOGGER_MONITOR_THRESHOLD_EVENTS=ON"
EXTRA_OECMAKE += "-DREDFISH_LOG_MONITOR_PULSE_EVENTS=ON"
#EXTRA_OECMAKE += "-DSEL_LOGGER_MONITOR_WATCHDOG_EVENTS=ON"
#EXTRA_OECMAKE += "-DSEL_LOGGER_SEND_TO_LOGGING_SERVICE=ON"

SRC_URI += "file://0001-Change-ipmi_sel-location-to-persistent-folder.patch"
