# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_PRIORITY = "8"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ai1"
BBFILE_PATTERN_ai1 = "^${LAYERDIR}/"
LAYERVERSION_ai1 = "1"
LAYERSERIES_COMPAT_ai1 = "kirkstone langdale honister"
