# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "cmdale-layer"
BBFILE_PATTERN_cmdale-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_cmdale-layer = "5"
LAYERSERIES_COMPAT_cmdale-layer = "nanbield scarthgap"
