KMACHINE = "aspeed"
MACHINE = "ai1"
KERNEL_DEVICETREE = "${KMACHINE}-yandex-${MACHINE}.dtb"

require meta-common/conf/yandex-g5.conf

IMAGE_INSTALL:append = "intel-asd cpld-updater nvme-cooler host-error-monitor crashdump-bin"
